[formatting]

align_entries         = true
allowed_blank_lines   = 1
array_trailing_comma  = true
compact_arrays        = true
compact_inline_tables = false
crlf                  = false
indent_string         = "  "
indent_tables         = true
reorder_arrays        = true
reorder_keys          = true
