format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
"""

right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$kubernetes\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$docker_context\
$vagrant\
$zig\
$buf\
$nix_shell\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'
symbol = '🅰 '

[aws.region_aliases]
us-east-1 = 'va'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = ' '
style = 'blue bold'

[directory]
read_only = ''

[docker_context]
disabled = true

[package]
disabled = true

[character]
vimcmd_symbol = '[V](bold green) '

[git_status]
disabled = true

[python]
format = 'via [${symbol}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
style = 'green bold'

[kubernetes]
disabled = false
style = 'cyan bold'	
format = '[$symbol$context( \($namespace\))]($style) '
