"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
"""

right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$kubernetes\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$docker_context\
$vagrant\
$zig\
$buf\
$nix_shell\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style  = 'bold yellow'
symbol = '🅰 '
  [aws.region_aliases]
  us-east-1 = 'va'

[azure]
disabled = false
format   = 'on [$symbol($subscription)]($style) '
style    = 'blue bold'
symbol   = ' '

[directory]
read_only = ''

[docker_context]
disabled = true

[package]
disabled = true

[character]
vimcmd_symbol = '[V](bold green) '

[git_status]
disabled = true

[python]
format = 'via [${symbol}(${version} )(\($virtualenv\) )]($style)'
style  = 'green bold'
symbol = ' '

[kubernetes]
disabled = false
format   = '[$symbol$context( \($namespace\))]($style) '
style    = 'cyan bold'

[gcloud]
disabled = true
symbol   = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
AOSC             = " "
AlmaLinux        = " "
Alpaquita        = " "
Alpine           = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CachyOS          = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
Nobara           = " "
OpenBSD          = "󰈺 "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
RedHatEnterprise = " "
Redhat           = " "
Redox            = "󰀘 "
RockyLinux       = " "
SUSE             = " "
Solus            = "󰠳 "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "
openSUSE         = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
